// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import frc.robot.subsystems.*;

/**
 *
 */
public class AutonavSlalomPath extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutonavSlalomPath() {

        /*             ****INITIAL ROBOT PLACEMENT****
          Robot should start at a 45 degree angle against the bottom right
          corner of the start box. Front right corner should be (3/sqrt(2))
          ft up and back right corner should be (3/sqrt(2)) ft left
          
        */

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.
        addSequential(new DriveXFeet(5 * Math.sqrt(2))); //1
        addSequential(new TurnNDegreesAbsolute(45)); //2
        addSequential(new DriveXFeet(12.5)); //3
        addSequential(new TurnNDegreesAbsolute(90)); //4
        addSequential(new DriveXFeet(5 * Math.sqrt(2))); //5
        addSequential(new TurnNDegreesAbsolute(0)); //6
        addSequential(new DriveXFeet(5 / Math.sqrt(2))); //7
        addSequential(new TurnNDegreesAbsolute(-90)); //8
        addSequential(new DriveXFeet(5 / Math.sqrt(2))); //9
        addSequential(new TurnNDegreesAbsolute(0)); //10
        addSequential(new DriveXFeet(5 / Math.sqrt(2) * -1)); //11
        addSequential(new TurnNDegreesAbsolute(45)); //12
        addSequential(new DriveXFeet(-12.5)); //13
        addSequential(new TurnNDegreesAbsolute(90)); //14
        addSequential(new DriveXFeet(5 * Math.sqrt(2) * -1)); //15
        
        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
    } 
}
